# Generated by Django 3.1.2 on 2020-10-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture_id',
        ),
    ]
